<?php

declare(strict_types=1);

namespace RobinsonRyan\HeyYou\Support;

use Illuminate\Database\Schema\Blueprint;
use RobinsonRyan\HeyYou\Contracts\IdentifierGenerator;

final class AutoIncrementGenerator implements IdentifierGenerator
{
    public function generate(): string|int
    {
        // Auto-increment IDs are generated by the database
        // This method is not typically called for auto-increment
        return 0;
    }

    public function columnDefinition(Blueprint $table, string $column): void
    {
        $table->id($column);
    }
}
